package com.example.groceryshoppingapplication.enums

enum class SubCategory(val value:String) {
    HERBS_AND_SEASONINGS("Herbs & Seasonings"),
    FRESH_FRUITS("Fresh Fruits"),
    ORGANIC_FRUITS_AND_VEGETABLES("Organic Fruits & Vegetables"),
    CUTS_AND_SPROUTS("Cuts & Sprouts"),
    EXOTIC_FRUITS_AND_VEGGIES("Exotic Fruits & Veggies"),
    FLOWER_BOUQUETS_BUNCHES("Flower Bouquets, Bunches"),
    ATTA_FLOURS_AND_SOOJI("Atta Flours & Sooji"),
    RICE_AND_RICE_PRODUCTS("Rice & Rice Products"),
    DALS_AND_PULSES("Dals & Pulses"),
    ORGANIC_STAPLES("Organic Staples"),
    EDIBLE_OILS_AND_GHEE("Edible Oils & Ghee"),
    SALT_SUGAR_AND_JAGGERY("Salt Sugar & Jaggery"),
    MASALAS_AND_SPICES("Masalas & Spices"),
    DRY_FRUITS("Dry Fruits"),
    DAIRY("Dairy"),
    BREADS_AND_BUNS("Breads & Buns"),
    NON_DAIRY("Non Dairy"),
    GOURMET_BREADS("Gourmet Breads"),
    COOKIES_RUSK_AND_KHARI("Cookies, Rusk & Khari"),
    ICE_CREAMS_AND_DESSERTS("Ice Creams & Desserts"),
    BAKERY_SNACKS("Bakery Snacks"),
    CAKES_AND_PASTRIES("Cakes & Pastries"),
    ENERGY_AND_SOFT_DRINKS("Energy & Soft Drinks"),
    WATER("Water"),
    HEALTH_DRINK_SUPPLEMENT("Health Drink, Supplement"),
    TEA("Tea"),
    COFFEE("Coffee"),
    FRUIT_JUICES_AND_DRINKSNOODLE_PASTA_VERMICELLI("Fruit Juices & DrinksNoodle, Pasta, Vermicelli"),
    BREAKFAST_CEREALS("Breakfast Cereals"),
    FROZEN_VEGGIES_AND_SNACKS("Frozen Veggies & Snacks"),
    BISCUITS_AND_COOKIES("Biscuits & Cookies"),
    SNACKS_AND_NAMKEEN("Snacks & Namkeen"),
    SPREADS_SAUCES_KETCHUP("Spreads, Sauces, Ketchup"),
    READY_TO_COOK_AND_EAT("Ready To Cook & Eat"),
    CHOCOLATES_AND_CANDIES("Chocolates & Candies"),
    PICKLES_AND_CHUTNEY("Pickles & Chutney"),
    INDIAN_MITHAIORAL_CARE("Indian MithaiOral Care"),
    FEMININE_HYGIENE("Feminine Hygiene"),
    BATH_AND_HAND_WASH("Bath & Hand Wash"),
    HAIR_CARE("Hair Care"),
    HEALTH_AND_MEDICINE("Health & Medicine"),
    MENS_GROOMING("Men's Grooming"),
    SKIN_CARE("Skin Care"),
    MAKEUP("Makeup"),
    FRAGRANCES_AND_DEOSDETERGENTS_AND_DISHWASH("Fragrances & DeosDetergents & Dishwash"),
    ALL_PURPOSE_CLEANERS("All Purpose Cleaners"),
    DISPOSABLES_GARBAGE_BAG("Disposables, Garbage Bag"),
    FRESHENERS_AND_REPELLENTS("Fresheners & Repellents"),
    MOPS_BRUSHES_AND_SCRUBS("Mops, Brushes & Scrubs"),
    CAR_AND_SHOE_CARE("Car & Shoe Care"),
    POOJA_NEEDS("Pooja Needs"),
    STATIONERY("Stationery"),
    BINS_AND_BATHROOM_WARE("Bins & Bathroom Ware"),
    PARTY_AND_FESTIVE_NEEDSPET_FOOD_AND_ACCESSORIES("Party & Festive NeedsPet Food & Accessories"),
    APPLIANCES_AND_ELECTRICALS("Appliances & Electricals"),
    STEEL_UTENSILS("Steel Utensils"),
    GARDENING("Gardening"),
    KITCHEN_ACCESSORIES("Kitchen Accessories"),
    COOKWARE_AND_NON_STICK("Cookware & Non Stick"),
    FLASK_AND_CASSEROLE("Flask & Casserole"),
    BAKEWARE("Bakeware"),
    CROCKERY_AND_CUTLERY("Crockery & Cutlery"),
    STORAGE_AND_ACCESSORIESEGGS("Storage & AccessoriesEggs"),
    POULTRY("Poultry"),
    SAUSAGES_BACON_AND_SALAMI("Sausages, Bacon & Salami"),
    MUTTON_AND_LAMB("Mutton & Lamb"),
    MARINADES("Marinades"),
    FISH_AND_SEAFOOD("Fish & Seafood"),
    PORK_AND_OTHER_MEATSOILS_AND_VINEGAR("Pork & Other MeatsOils & Vinegar"),
    DAIRY_AND_CHEESE("Dairy & Cheese"),
    SNACKS_DRY_FRUITS_NUTS("Snacks, Dry Fruits, Nuts"),
    PASTA_SOUP_AND_NOODLES("Pasta, Soup & Noodles"),
    CEREALS_AND_BREAKFAST("Cereals & Breakfast"),
    SAUCES_SPREADS_AND_DIPS("Sauces, Spreads & Dips"),
    CHOCOLATES_AND_BISCUITS("Chocolates & Biscuits"),
    COOKING_AND_BAKING_NEEDS("Cooking & Baking Needs"),
    DRINKS_AND_BEVERAGES("Drinks & Beverages"),
    TINNED_AND_PROCESSED_FOODDIAPERS_AND_WIPES("Tinned & Processed FoodDiapers & Wipes"),
    BABY_BATH_AND_HYGIENE("Baby Bath & Hygiene"),
    BABY_FOOD_AND_FORMULA("Baby Food & Formula"),
    MOTHERS_AND_MATERNITY("Mothers & Maternity"),
    FEEDING_AND_NURSING("Feeding & Nursing"),
    BABY_ACCESSORIES("Baby Accessories"),
}